; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

; Teensy 4.1 CPU is by default clocked to 600MHz.
; You can change the value here to overclock it, but you may need a heatsink for stability.
; Mostly leaving this here just as an option for your personal use, at your own risk.
; board_build.f_cpu = 816000000L ; Overclock to 816MHz (requires adequate cooling)
; board_build.f_cpu = 720000000L ; Overclock to 720MHz (most can handle without cooling)

build_flags = 
  -D USB_SERIAL_HID
  -Ofast
  -flto
  -fstrict-aliasing
extra_scripts = scripts/8kHz_polling.py

; Library dependencies
; PlatformIO will automatically download these libraries
lib_deps = 
	adafruit/Adafruit GFX Library
	adafruit/Adafruit SSD1306
	thomasfredericks/Bounce2