name: Build Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio

    - name: Run PlatformIO Build
      run: pio run -e teensy41

    - name: Upload Firmware Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: .pio/build/teensy41/firmware.hex